var pessoas = [
    {"id": 1, "name": "Xenos", "age": 53, "city" : "Montes Claros"},
    {"id": 2, "name": "Honorato", "age": 46, "city" : "Nova Lima"},
    {"id": 3, "name": "Knox", "age": 77, "city" : "Nova Serrana"},
    {"id": 4, "name": "Olympia", "age": 39, "city" : "Passos"},
    {"id": 5, "name": "Graham", "age": 45, "city" : "Teófilo Otoni"},
    {"id": 6, "name": "Dennis", "age": 45, "city" : "Divinópolis"},
    {"id": 7, "name": "Pandora", "age": 22, "city" : "Montes Claros"},
    {"id": 8, "name": "Jillian", "age": 39, "city" : "Sete Lagoas"},
    {"id": 9, "name": "Magee", "age": 62, "city" : "Belo Horizonte"},
    {"id": 10, "name": "Amber", "age": 28, "city" : "Nova Lima"},
    {"id": 11, "name": "Shoshana", "age": 62, "city" : "Vespasiano"},
    {"id": 12, "name": "Deborah", "age": 29, "city" : "Pouso Alegre"},
    {"id": 13, "name": "Garth", "age": 58, "city" : "Belo Horizonte"},
    {"id": 14, "name": "Ella", "age": 52, "city" : "Betim"},
    {"id": 15, "name": "Kirk", "age": 76, "city" : "Montes Claros"},
    {"id": 16, "name": "Hunter", "age": 53, "city" : "Itajubá"},
    {"id": 17, "name": "Leonard", "age": 47, "city" : "Poços de Caldas"},
    {"id": 18, "name": "Cleo", "age": 52, "city" :"Patos de Minas"},
    {"id": 19, "name": "Cameron", "age": 22, "city" : "Contagem"},
    {"id": 20, "name": "Pamela", "age": 64, "city" : "Nova Lima"},
    {"id": 21, "name": "Daphne", "age": 33, "city" : "Paracatu"},
    {"id": 22, "name": "Roth", "age": 41, "city" : "Vespasiano"},
    {"id": 23, "name": "Alec", "age": 32, "city" : "Santa Luzia"},
    {"id": 24, "name": "Lawrence", "age": 25, "city" : "Uberlândia"},
    {"id": 25, "name": "Winifred", "age": 29, "city" : "Contagem"},
    {"id": 26, "name": "Shannon", "age": 28, "city" : "Betim"},
    {"id": 27, "name": "Sonia", "age": 61, "city" : "Montes Claros"},
    {"id": 28, "name": "Preston", "age": 58, "city" : "Ubá"},
    {"id": 29, "name": "Stephanie", "age": 26, "city" : "Belo Horizonte"},
    {"id": 30, "name": "Briar", "age": 46, "city" : "Contagem"},
    {"id": 31, "name": "Valentine", "age": 47, "city" : "Ibirité"},
    {"id": 32, "name": "Nichole", "age": 69, "city" : "Sete Lagoas"},
    {"id": 33, "name": "Chaim", "age": 43, "city" : "Betim"},
    {"id": 34, "name": "Jescie", "age": 37, "city" : "Montes Claros"},
    {"id": 35, "name": "Lacey", "age": 23, "city" : "Belo Horizonte"},
    {"id": 36, "name": "Blaine", "age": 20, "city" : "Sete Lagoas"},
    {"id": 37, "name": "Blaze", "age": 66, "city" : "Governador Valadares"},
    {"id": 38, "name": "Zachery", "age": 45, "city" : "Uberlândia"},
    {"id": 39, "name": "Shad", "age": 78, "city" : "Patos de Minas"},
    {"id": 40, "name": "Kendall", "age": 23, "city" : "Montes Claros"},
    {"id": 41, "name": "Dalton", "age": 47, "city" : "Montes Claros"},
    {"id": 42, "name": "Violet", "age": 59, "city" : "Paracatu"},
    {"id": 43, "name": "Charissa", "age": 38, "city" : "Lavras"},
    {"id": 44, "name": "Jarrod", "age": 44, "city" : "Araxá"},
    {"id": 45, "name": "Maryam", "age": 38, "city" : "Santa Luzia"},
    {"id": 46, "name": "Leigh", "age": 22, "city" : "Divinópolis"},
    {"id": 47, "name": "Iris", "age": 57, "city" : "Belo Horizonte"},
    {"id": 48, "name": "Castor", "age": 57, "city" : "São João del Rei"},
    {"id": 49, "name": "Jocelyn", "age": 78, "city" :"Araxá"},
    {"id": 50, "name": "Tyrone", "age": 50, "city" : "Ribeirão das Neves"},
    {"id": 51, "name": "Colby", "age": 22, "city" : "Montes Claros"},
    {"id": 52, "name": "Timothy", "age": 78, "city" : "Santa Luzia"},
    {"id": 53, "name": "Kelly", "age": 76, "city" : "Uberlândia"},
    {"id": 54, "name": "Jeremy", "age": 50, "city" : "Belo Horizonte"},
    {"id": 55, "name": "Trevor", "age": 79, "city" : "Montes Claros"},
    {"id": 56, "name": "Walker","age": 51, "city" : "Nova Lima"},
    {"id": 57, "name": "Kareem", "age": 59, "city" : "Montes Claros"},
    {"id": 58, "name": "Gavin", "age": 69, "city" : "Nova Lima"},
    {"id": 59, "name": "Linda", "age": 49, "city" : "Santa Luzia"},
    {"id": 60, "name": "Lev", "age": 31, "city" : "Betim"},
    {"id": 61, "name": "Yardley", "age": 80, "city" : "Montes Claros"},
    {"id": 62, "name": "Nasim", "age": 30, "city" : "Coronel Fabriciano"},
    {"id": 63, "name": "Tanner", "age": 72, "city" : "Conselheiro Lafaiete"},
    {"id": 64, "name": "Daquan", "age": 48, "city" : "Betim"},
    {"id": 65, "name": "Rhonda", "age": 57, "city" : "Belo Horizonte"},
    {"id": 66, "name": "Kendall", "age": 46, "city" : "Uberlândia"},
    {"id": 67, "name": "Lars", "age": 22, "city" : "Montes Claros"},
    {"id": 68, "name": "Jack", "age": 69, "city" : "Nova Lima"},
    {"id": 69, "name": "Sean", "age": 38, "city" : "Belo Horizonte"},
    {"id": 70, "name": "Hall", "age": 35, "city" : "Uberlândia"},
    {"id": 71, "name": "Molly", "age": 19, "city" : "Montes Claros"},
    {"id": 72, "name": "Charlotte", "age": 34, "city" : "Coronel Fabriciano"},
    {"id": 73, "name": "Keith", "age": 45, "city" : "Contagem"},
    {"id": 74, "name": "Quinlan", "age": 57, "city" : "Ubá"},
    {"id": 75, "name": "Francis", "age": 80, "city" : "Barbacena"},
    {"id": 76, "name": "Abel", "age": 54, "city" : "Betim"},
    {"id": 77, "name": "Jonas", "age": 53, "city" : "Belo Horizonte"},
    {"id": 78, "name": "Keegan", "age": 66, "city" : "Sabará"},
    {"id": 79, "name": "Yen", "age": 32, "city" : "Belo Horizonte"},
    {"id": 80, "name": "Barbara","age": 27, "city" : "Ituiutaba"},
    {"id": 81, "name": "Simone", "age": 45, "city" : "Montes Claros"},
    {"id": 82, "name": "Regina", "age": 37, "city" : "Pará de Minas"},
    {"id": 83, "name": "Leilani", "age": 68, "city" : "Itaúna"},
    {"id": 84, "name": "Chase", "age": 68, "city" : "Araxá"},
    {"id": 85, "name": "Ashton", "age": 34, "city" : "Uberaba"},
    {"id": 86, "name": "Myra", "age": 35, "city" : "Belo Horizonte"},
    {"id": 87, "name": "Raja", "age": 39, "city" : "Santa Luzia"},
    {"id": 88, "name": "Malik", "age": 23, "city" : "Uberlândia"},
    {"id": 89, "name": "Hayfa", "age": 47, "city" : "Montes Claros"},
    {"id": 90, "name": "Brittany", "age": 57, "city" : "Betim"},
    {"id": 91, "name": "Aubrey", "age": 61, "city" : "Contagem"},
    {"id": 92, "name": "Cyrus", "age": 41, "city" : "Governador Valadares"},
    {"id": 93, "name": "Carlos", "age": 73, "city" : "Ribeirão das Neves"},
    {"id": 94, "name": "Christopher", "age": 32, "city" : "Juiz de Fora"},
    {"id": 95, "name": "Kerry", "age": 36, "city" : "Belo Horizonte"},
    {"id": 96, "name": "Jermaine", "age": 27, "city" : "Santa Luzia"},
    {"id": 97, "name": "Addison", "age": 40, "city" : "Sabará"}, 
    {"id": 98, "name": "Joel", "age": 23, "city" : "Varginha"}, 
    {"id": 99, "name": "Irene", "age": 60, "city" : "São João del Rei"}, 
    {"id": 100, "name": "Carla", "age": 41, "city" : "Montes Claros"}
];

document.getElementById("body").onload = function () { createTable() };

function createTable () {
    var string = JSON.stringify(pessoas);
    var meusdados = JSON.parse(string);
    var conteudo = ' <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">'; 
    conteudo +=' <thead> <tr> <th>Id</th> <th>Nome</th> <th>Idade/th> <th>Cidade/th> <th>Checkbox</th> </tr> </thead> <tbody>';
    for (var i = 0; i < meusdados.length; i++ ) {
        conteudo += "<tr> <td>" +meusdados[i].id+ "</td> <td>" +meusdados[i].name+ "</td> <td>" +meusdados[i].age+ "</td> "; 
        conteudo += '<td> '+meusdados[i].city+' </td> <td> <input type="checkbox" id="scales'+i+'" name="checkbox'+i+'"></td> </tr> ';
    }
    conteudo += "</tbody> <tfoot> <tr> <th>Id</th> <th>Nome</th> <th>Idade/th> <th>Cidade/th> <th>Checkbox</th> </tr> </tfoot> </table>";
    console.log(conteudo);
    document.getElementById("tablePrint").innerHTML = conteudo;
}